apiVersion: apps/v1
kind: Deployment
metadata:
  name: button-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: button
  template:
    metadata:
      labels:
        app: button
    spec:
      containers:
      - name: button-container
        image: button-yura
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

