
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t button-yura .

      - name: Run tests inside container
        run: docker run button-yura pytest tests/

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/button_yura

            git pull

            docker stop $(docker ps -q) || true
            docker rm $(docker ps -aq) || true

            docker build -t button-yura .
            docker run -d -p 5000:5000 button-yura 

      - name: Simulate Kubernetes deploy
        run: |
          echo "Applying Kubernetes manifests..."
          cat k8s/deployment.yaml
          cat k8s/service.yaml
